services:
  database:
    image: mariadb:10.4.32
    environment:
      MARIADB_DATABASE: ${MARIADB_DB:-ecoride}
      MARIADB_USER: ${MARIADB_USER:-root}
      MARIADB_PASSWORD: ""
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-EcoRide}
      # pas de MONGO_INITDB_ROOT_USERNAME/PASSWORD → pas d’auth
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/symfony
    depends_on:
      database:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/symfony
    depends_on:
      - symfony


volumes:
  database_data:
  mongodb_data:

